name: media_probe_mobile_app
description: Media Probe is a revolutionizing online media. They aim to be the one stop shop for all relevant mediaarticles, which can be personalised to users. They aim to reach all corners of the globe and be easily accessible. They have requested for a mobile application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png
